### ISSUE TITLE
`git` tag dates reset

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/powerloader#150]
Not really an issue - just opening to let you know it appears all tag dates have been reset:

![image](https://user-images.githubusercontent.com/881019/213915228-9812e1ea-bb12-4e3e-81a0-83e38d28db91.png)

...or it's a GitHub UI bug!

**Comment by dhirschfeld** [comment]
Anyway, now you know...

**Comment by JohanMabille** [comment]
@dhirschfeld I had a weird bug when pushing last release, it pushed all the tags from mamba. So I had to remove them (unfotunately with a too greedy regexp) and reapply them. I applied them on the same commit as before, but the dates changed.
